spring:
  application:
    name: spring_exercise_6
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

application:
  user: admin
  password: password
  secret: THIS_IS_SUPER_SECRET_KEY